/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lpoo_sistemaestacionamentoifsul.estacionamentoifsul.menu;

/**
 *
 * @author 20241pf.cc0029
 */


public class MainJFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        barraMenu = new javax.swing.JMenuBar();
        miBotaoCadastro = new javax.swing.JMenu();
        miBotaoPessoa = new javax.swing.JMenuItem();
        miBotaoVeiculo = new javax.swing.JMenuItem();
        miBotaoMovimentacao = new javax.swing.JMenu();
        miBotaoAjuda = new javax.swing.JMenu();
        miAjudaSobre = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barraMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        miBotaoCadastro.setText("Cadastro");

        miBotaoPessoa.setText("Pessoa");
        miBotaoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBotaoPessoaActionPerformed(evt);
            }
        });
        miBotaoCadastro.add(miBotaoPessoa);

        miBotaoVeiculo.setText("Veiculo");
        miBotaoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBotaoVeiculoActionPerformed(evt);
            }
        });
        miBotaoCadastro.add(miBotaoVeiculo);

        barraMenu.add(miBotaoCadastro);

        miBotaoMovimentacao.setText("Movimentação");
        barraMenu.add(miBotaoMovimentacao);

        miBotaoAjuda.setText("Ajuda");
        miBotaoAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBotaoAjudaActionPerformed(evt);
            }
        });

        miAjudaSobre.setText("Sobre");
        miAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAjudaSobreActionPerformed(evt);
            }
        });
        miBotaoAjuda.add(miAjudaSobre);

        barraMenu.add(miBotaoAjuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miBotaoAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBotaoAjudaActionPerformed

    }//GEN-LAST:event_miBotaoAjudaActionPerformed

    private void miAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAjudaSobreActionPerformed
         TelaSobre telaSobre = new TelaSobre(this, rootPaneCheckingEnabled);
         telaSobre.setVisible(true);
    }//GEN-LAST:event_miAjudaSobreActionPerformed

    private void miBotaoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBotaoPessoaActionPerformed
        TelaPessoa telaPessoa = new TelaPessoa();
        telaPessoa.setVisible(true);
    }//GEN-LAST:event_miBotaoPessoaActionPerformed

    private void miBotaoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBotaoVeiculoActionPerformed
        TelaVeiculo telaVeiculo = new TelaVeiculo();
        telaVeiculo.setVisible(true);
    }//GEN-LAST:event_miBotaoVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenuItem miAjudaSobre;
    private javax.swing.JMenu miBotaoAjuda;
    private javax.swing.JMenu miBotaoCadastro;
    private javax.swing.JMenu miBotaoMovimentacao;
    private javax.swing.JMenuItem miBotaoPessoa;
    private javax.swing.JMenuItem miBotaoVeiculo;
    // End of variables declaration//GEN-END:variables
}
