/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package lpoo_sistemaestacionamentoifsul.estacionamentoifsul.menu;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import javax.swing.DefaultListModel;
import lpoo_sistemaestacionamentoifsul.estacionamentoifsul.dao.PersistenciaJPA;
import model.Modelo;
import model.Pessoa;
import model.TipoVeiculo;
import model.Veiculo;
import model.VeiculoOficial;
/**
 *
 * @author adrie
 */
public class TelaCadastroVeiculo extends javax.swing.JFrame {
    PersistenciaJPA jpa;
    Veiculo veiculo;
    VeiculoOficial oficial;
    
    private List<Pessoa> listaP;
    private List<Modelo> listaM;
    
    public Veiculo getVeiculo(){
        return veiculo;
    }
    
    public void setVeiculo(Veiculo veiculo){
        this.veiculo = veiculo;
        textoPlaca.setText(veiculo.getPlaca());
        textoCor.setText(veiculo.getCor());
        cmbTipoVeiculo.setSelectedItem(veiculo.getTipo());
        cmbProprietario.setSelectedItem(veiculo.getProprietario());
        cmbModelo.setSelectedItem(veiculo.getModelo());
    }
    /**
     * Creates new form TelaCadastroVeiculo
     */
    public TelaCadastroVeiculo(java.awt.Frame parent, boolean modal) {
        initComponents();
        jpa = new PersistenciaJPA();
        carregarCmbTipo();
        carregarCmbProprietario();
        carregarCmbModelo();
        verificaOficial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelPlaca = new javax.swing.JLabel();
        labelTipoVeiculo = new javax.swing.JLabel();
        labelCor = new javax.swing.JLabel();
        labelProprietario = new javax.swing.JLabel();
        labelModelo = new javax.swing.JLabel();
        textoPlaca = new javax.swing.JTextField();
        textoCor = new javax.swing.JTextField();
        cbOficial = new javax.swing.JCheckBox();
        labelOficial = new javax.swing.JLabel();
        cmbTipoVeiculo = new javax.swing.JComboBox<>();
        cmbProprietario = new javax.swing.JComboBox<>();
        cmbModelo = new javax.swing.JComboBox<>();
        botaoMais = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        labelChassi = new javax.swing.JLabel();
        labelRenavan = new javax.swing.JLabel();
        textoChassi = new javax.swing.JTextField();
        textoRenavan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setText("Cadastro Veículos");

        labelPlaca.setText("Placa:");

        labelTipoVeiculo.setText("Tipo de Veículo:");

        labelCor.setText("Cor:");

        labelProprietario.setText("Proprietário:");

        labelModelo.setText("Modelo:");

        cbOficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOficialActionPerformed(evt);
            }
        });

        labelOficial.setText("Oficial:");

        botaoMais.setText("+");
        botaoMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMaisActionPerformed(evt);
            }
        });

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        labelChassi.setText("Chassi:");

        labelRenavan.setText("Renavan:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTipoVeiculo)
                                    .addComponent(labelPlaca)
                                    .addComponent(labelCor)
                                    .addComponent(labelProprietario)
                                    .addComponent(labelModelo)
                                    .addComponent(labelOficial))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbOficial)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(textoRenavan, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoChassi, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbTipoVeiculo, javax.swing.GroupLayout.Alignment.LEADING, 0, 95, Short.MAX_VALUE)
                                            .addComponent(textoCor, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbProprietario, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbModelo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoMais)))))
                        .addContainerGap(105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoCancelar)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelChassi)
                            .addComponent(labelRenavan))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlaca)
                    .addComponent(textoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoVeiculo)
                    .addComponent(cmbTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCor)
                    .addComponent(textoCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProprietario)
                    .addComponent(cmbProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModelo)
                    .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoMais))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOficial)
                    .addComponent(cbOficial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelChassi)
                    .addComponent(textoChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRenavan)
                    .addComponent(textoRenavan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoCancelar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbOficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOficialActionPerformed
        verificaOficial();
    }//GEN-LAST:event_cbOficialActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if(!cbOficial.isSelected()){
            if(veiculo == null){
                veiculo = new Veiculo();
            }
            veiculo.setPlaca(textoPlaca.getText());
            veiculo.setCor(textoCor.getText());
            veiculo.setModelo((Modelo)cmbModelo.getSelectedItem());
            veiculo.setProprietario((Pessoa)cmbProprietario.getSelectedItem());
            veiculo.setTipo((TipoVeiculo)cmbTipoVeiculo.getSelectedItem());
            
            jpa.conexaoAberta();
            try {
                jpa.persist(veiculo);
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(TelaCadastroPessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            jpa.fecharConexao();
        }else{
            if(oficial == null){
                oficial = new VeiculoOficial();
            }
            oficial.setPlaca(textoPlaca.getText());
            oficial.setCor(textoCor.getText());
            oficial.setModelo((Modelo)cmbModelo.getSelectedItem());
            oficial.setTipo((TipoVeiculo)cmbTipoVeiculo.getSelectedItem());
            oficial.setChassi(textoChassi.getText());
            oficial.setRenavan(textoRenavan.getText());
            
            jpa.conexaoAberta();
            try {
                jpa.persist(oficial);
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(TelaCadastroPessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            jpa.fecharConexao();
        }
        dispose();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMaisActionPerformed
        TelaCadastroModelo telaCadastro;
        telaCadastro = new TelaCadastroModelo(this, rootPaneCheckingEnabled);
        telaCadastro.setVisible(true);
        carregarCmbTipo();
        carregarCmbProprietario();
        carregarCmbModelo();
    }//GEN-LAST:event_botaoMaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroVeiculo dialog = new TelaCadastroVeiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoMais;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JCheckBox cbOficial;
    private javax.swing.JComboBox<Modelo> cmbModelo;
    private javax.swing.JComboBox<Pessoa> cmbProprietario;
    private javax.swing.JComboBox<TipoVeiculo> cmbTipoVeiculo;
    private javax.swing.JLabel labelChassi;
    private javax.swing.JLabel labelCor;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelOficial;
    private javax.swing.JLabel labelPlaca;
    private javax.swing.JLabel labelProprietario;
    private javax.swing.JLabel labelRenavan;
    private javax.swing.JLabel labelTipoVeiculo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textoChassi;
    private javax.swing.JTextField textoCor;
    private javax.swing.JTextField textoPlaca;
    private javax.swing.JTextField textoRenavan;
    // End of variables declaration//GEN-END:variables

    private void carregarCmbTipo() {
        cmbTipoVeiculo.removeAllItems();
        for(TipoVeiculo t : TipoVeiculo.values()){
            cmbTipoVeiculo.addItem(t);
        }
    }
    
    private void carregarCmbProprietario() {
        cmbProprietario.removeAllItems();
        
        listaP = new ArrayList<>();
        
        jpa.conexaoAberta();
        
        listaP.addAll(jpa.getPessoas());
        
        jpa.fecharConexao();
        
        for(Pessoa p : listaP){
            cmbProprietario.addItem(p);
        }
    }

    private void carregarCmbModelo() {
        cmbModelo.removeAllItems();
        jpa.conexaoAberta();
        
        listaM = new ArrayList<>();
        
        listaM.addAll(jpa.getModelos());
        listaM.toString();
        
        jpa.fecharConexao();
        
        for(Modelo m : listaM){
            cmbModelo.addItem(m);
        }
    }
    
    public void verificaOficial(){
        if(cbOficial.isSelected()){
            cmbProprietario.setEnabled(false);
            textoRenavan.setEnabled(true);
            textoChassi.setEnabled(true);
        }else{
            cmbProprietario.setEnabled(true);
            textoRenavan.setEnabled(false);
            textoChassi.setEnabled(false);
        }
    }
}
